image: ruby:2.5.1
services:
  - postgres:9.5
stages:
  - build
  - deploy_staging

variables:
  POSTGRES_DB: telegram_test
  POSTGRES_USER: telegram
  POSTGRES_PASSWORD: telegram
  DB_HOST: postgres

job_build:
  stage: build
  script:
    - "bundle install"
    - "RACK_ENV=test rake"

job_deploy_staging:
  stage: deploy_staging
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
