source 'https://rubygems.org'

ruby '2.5.1'

gem 'byebug'
gem 'cucumber'
gem 'guard'
gem 'guard-rspec'
gem 'json'
gem 'pg', '~> 0.18'
gem 'rack-test', require: 'rack/test'
gem 'rake'
gem 'rb-readline'
gem 'rspec'
gem 'rspec_junit_formatter'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'sequel'
gem 'sinatra', '1.4.7'
